import type {
  AlignmentStatus,
  CentreLevelConfig,
  HeadVariantId,
  LevelConfig,
  LevelId,
  ScrewId,
} from './types'

const SCREW_1_COLOR = 'var(--color-screw-1)'
const SCREW_2_COLOR = 'var(--color-screw-2)'
const SCREW_3_COLOR = 'var(--color-screw-3)'

export const CENTRE_STATUS_LABELS: Record<AlignmentStatus, string> = {
  aligned: 'Sejajar',
  near: 'Hampir Sejajar',
  unaligned: 'Belum Sejajar',
}

const LEVEL_1: CentreLevelConfig = {
  id: 'level1',
  number: 1,
  kind: 'centre',
  shortName: 'Cermin',
  tabLabel: 'Level 1 · Cermin',
  refHeading: 'Cermin / Mirror Mount',
  targetHeading: 'Kawasan Sasaran Beam',
  statusLabels: CENTRE_STATUS_LABELS,
  successMessage: 'Tahniah! Beam telah berada di tengah sasaran.',
  image: {
    path: 'images/k40-mirror-mount.png',
    width: 525,
    height: 705,
    alt: 'Mirror mount laser dengan tiga skru pelarasan',
  },
  refImageClass: 'w-full max-w-[260px] sm:max-w-[300px] lg:max-w-[190px]',
  adjustStageClass: 'max-w-[256px] px-11 sm:max-w-[330px] sm:px-12',
  screwOrder: ['screw1', 'screw3', 'screw2'],
  screws: {
    screw1: {
      id: 'screw1',
      number: 1,
      title: 'Skru 1 – Atas / Bawah',
      description: 'Gerakkan beam atas atau bawah',
      colorVar: SCREW_1_COLOR,
      axis: 'vertical',
      minusLabel: 'ke atas',
      plusLabel: 'ke bawah',
      movement: {
        minus: { x: 0, y: 1, description: 'Atas' },
        plus: { x: 0, y: -1, description: 'Bawah' },
      },
      knob: { top: '22%', left: '86.5%' },
      badge: { top: '22%', left: '65%' },
      refBadge: { top: '14%', left: '104%' },
      refArrow: { top: '29%', left: '104%' },
      pod: { side: 'right', top: '18%' },
      guide: 'Skru 1 gerakkan beam atas/bawah',
    },
    screw2: {
      id: 'screw2',
      number: 2,
      title: 'Skru 2 – Diagonal',
      extraTitle: '(kiri atas ↔ kanan bawah)',
      description: 'Gerakkan beam secara diagonal',
      colorVar: SCREW_2_COLOR,
      axis: 'diagonal',
      minusLabel: 'ke kanan bawah',
      plusLabel: 'ke kiri atas',
      movement: {
        minus: { x: 1, y: -1, description: 'Kanan bawah' },
        plus: { x: -1, y: 1, description: 'Kiri atas' },
      },
      knob: { top: '60%', left: '85%' },
      badge: { top: '60%', left: '64%' },
      refBadge: { top: '55%', left: '104%' },
      refArrow: { top: '70%', left: '104%' },
      pod: { side: 'right', top: '79%' },
      guide: 'Skru 2 gerakkan beam secara diagonal (kiri atas ↔ kanan bawah)',
    },
    screw3: {
      id: 'screw3',
      number: 3,
      title: 'Skru 3 – Kiri / Kanan',
      description: 'Gerakkan beam kiri atau kanan',
      colorVar: SCREW_3_COLOR,
      axis: 'horizontal',
      minusLabel: 'ke kiri',
      plusLabel: 'ke kanan',
      movement: {
        minus: { x: -1, y: 0, description: 'Kiri' },
        plus: { x: 1, y: 0, description: 'Kanan' },
      },
      knob: { top: '60%', left: '30%' },
      badge: { top: '50%', left: '16%' },
      refBadge: { top: '55%', left: '9%' },
      refArrow: { top: '68%', left: '8%' },
      pod: { side: 'left', top: '74%' },
      guide: 'Skru 3 gerakkan beam kiri/kanan',
    },
  },
}

const LEVEL_2: CentreLevelConfig = {
    id: 'level2',
    number: 2,
    kind: 'centre',
    shortName: 'Head',
    tabLabel: 'Level 2 · Head',
    refHeading: 'Cermin Head / Head Mirror',
    targetHeading: 'Kawasan Sasaran Beam',
    statusLabels: CENTRE_STATUS_LABELS,
    successMessage: 'Tahniah! Beam telah berada di tengah sasaran.',
    image: {
      path: 'images/laser-head-mirror.jpg',
      width: 760,
      height: 675,
      alt: 'Cermin pada head laser cutter dengan tiga skru pelarasan',
    },
    refImageClass: 'w-full max-w-[300px] sm:max-w-[330px] lg:max-w-[230px]',
    adjustStageClass: 'max-w-[350px] px-11 sm:max-w-[440px] sm:px-12',
    screwOrder: ['screw1', 'screw2', 'screw3'],
    screws: {
      screw1: {
        id: 'screw1',
        number: 1,
        title: 'Skru 1 – Atas / Bawah',
        extraTitle: '(kiri atas)',
        description: 'Gerakkan beam atas atau bawah',
        colorVar: SCREW_1_COLOR,
        axis: 'vertical',
        minusLabel: 'ke bawah',
        plusLabel: 'ke atas',
        movement: {
          minus: { x: 0, y: -1, description: 'Bawah' },
          plus: { x: 0, y: 1, description: 'Atas' },
        },
        knob: { top: '14%', left: '12%' },
        badge: { top: '14%', left: '26%' },
        refBadge: { top: '12%', left: '-6%' },
        refArrow: { top: '30%', left: '-6%' },
        pod: { side: 'left', top: '18%' },
        guide: 'Skru 1 (kiri atas) gerakkan beam atas/bawah',
      },
      screw2: {
        id: 'screw2',
        number: 2,
        title: 'Skru 2 – Atas / Bawah',
        extraTitle: '(kiri bawah)',
        description: 'Arah bertentangan dengan Skru 1',
        colorVar: SCREW_2_COLOR,
        axis: 'vertical',
        minusLabel: 'ke atas',
        plusLabel: 'ke bawah',
        movement: {
          minus: { x: 0, y: 1, description: 'Atas' },
          plus: { x: 0, y: -1, description: 'Bawah' },
        },
        knob: { top: '81%', left: '11%' },
        badge: { top: '81%', left: '26%' },
        refBadge: { top: '88%', left: '-6%' },
        refArrow: { top: '70%', left: '-6%' },
        pod: { side: 'left', top: '80%' },
        guide: 'Skru 2 (kiri bawah) gerakkan beam atas/bawah, bertentangan dengan Skru 1',
      },
      screw3: {
        id: 'screw3',
        number: 3,
        title: 'Skru 3 – Kiri / Kanan',
        extraTitle: '(kanan tengah)',
        description: 'Gerakkan beam kiri atau kanan',
        colorVar: SCREW_3_COLOR,
        axis: 'horizontal',
        minusLabel: 'ke kiri',
        plusLabel: 'ke kanan',
        movement: {
          minus: { x: -1, y: 0, description: 'Kiri' },
          plus: { x: 1, y: 0, description: 'Kanan' },
        },
        knob: { top: '47%', left: '88%' },
        badge: { top: '47%', left: '74%' },
        refBadge: { top: '34%', left: '106%' },
        refArrow: { top: '55%', left: '106%' },
        pod: { side: 'right', top: '47%' },
        guide: 'Skru 3 (kanan tengah) gerakkan beam kiri/kanan',
      },
    },
}

export const LEVELS: Record<LevelId, LevelConfig> = {
  level1: LEVEL_1,
  level2: LEVEL_2,
  level3: {
    id: 'level3',
    number: 3,
    kind: 'gantry',
    shortName: 'Gantry',
    tabLabel: 'Level 3 · Gerakan Gantry',
    targetHeading: 'Pandangan Atas Mesin',
    statusLabels: {
      aligned: 'Selesai',
      near: 'Sedang Bergerak',
      unaligned: 'Belum Selesai',
    },
    successMessage:
      'Tahniah! Y = 0 di belakang (atas) dan Y = 90 di depan (bawah) — cermin 2 bergerak bersama gantry.',
  },
  level4: {
    ...LEVEL_1,
    id: 'level4',
    number: 4,
    kind: 'straight',
    straightAxis: 'y',
    shortName: 'Beam Y',
    tabLabel: 'Level 4 · Beam Lurus Y Axis',
    refHeading: 'Cermin 1 / Mirror Mount',
    targetHeading: 'Acrylic pada Cermin 2',
    statusLabels: {
      aligned: 'Bertindih',
      near: 'Hampir Bertindih',
      unaligned: 'Belum Bertindih',
    },
    successMessage:
      'Tahniah! Tembakan Y=0 dan Y=90 sudah bertindih — beam kini selari dengan rel Y.',
  },
  level5: {
    ...LEVEL_1,
    id: 'level5',
    number: 5,
    kind: 'straight',
    straightAxis: 'x',
    shortName: 'Beam X',
    tabLabel: 'Level 5 · Beam Lurus X Axis',
    refHeading: 'Cermin 2 / Mirror Mount',
    targetHeading: 'Acrylic pada Head (Cermin 3)',
    statusLabels: {
      aligned: 'Bertindih',
      near: 'Hampir Bertindih',
      unaligned: 'Belum Bertindih',
    },
    successMessage:
      'Tahniah! Tembakan X=0 dan X=130 sudah bertindih — beam kini selari dengan gantry (paksi X).',
  },
}

export const LEVEL_ORDER: LevelId[] = [
  'level1',
  'level2',
  'level3',
  'level4',
  'level5',
]

// Level 2 menyokong dua jenis head — Mesin Bodor (asal) dan XD Laser.
// Setiap variant membawa gambar dan kelakuan skru sendiri.
export type HeadVariant = Pick<
  CentreLevelConfig,
  'image' | 'refImageClass' | 'adjustStageClass' | 'screwOrder' | 'screws'
> & { label: string }

export const HEAD_VARIANTS: Record<HeadVariantId, HeadVariant> = {
  bodor: {
    label: 'Bodor',
    image: LEVEL_2.image,
    refImageClass: LEVEL_2.refImageClass,
    adjustStageClass: LEVEL_2.adjustStageClass,
    screwOrder: LEVEL_2.screwOrder,
    screws: LEVEL_2.screws,
  },
  xd: {
    label: 'XD Laser',
    image: {
      path: 'images/xd-head-mirror.svg',
      width: 450,
      height: 549,
      alt: 'Head XD Laser dengan tiga skru pelarasan',
    },
    refImageClass: 'w-full max-w-[240px] sm:max-w-[270px] lg:max-w-[200px]',
    adjustStageClass: 'max-w-[300px] px-11 sm:max-w-[380px] sm:px-12',
    screwOrder: ['screw1', 'screw2', 'screw3'],
    screws: {
      screw1: {
        id: 'screw1',
        number: 1,
        title: 'Skru 1 – Atas / Bawah',
        extraTitle: '(atas kiri)',
        description: 'Gerakkan beam atas atau bawah',
        colorVar: SCREW_1_COLOR,
        axis: 'vertical',
        minusLabel: 'ke bawah',
        plusLabel: 'ke atas',
        movement: {
          minus: { x: 0, y: -1, description: 'Bawah' },
          plus: { x: 0, y: 1, description: 'Atas' },
        },
        knob: { top: '16%', left: '13%' },
        badge: { top: '16%', left: '31%' },
        refBadge: { top: '12%', left: '-6%' },
        refArrow: { top: '32%', left: '-6%' },
        pod: { side: 'left', top: '16%' },
        guide: 'Skru 1 (atas kiri) gerakkan beam atas/bawah',
      },
      screw2: {
        id: 'screw2',
        number: 2,
        title: 'Skru 2 – Diagonal',
        extraTitle: '(kiri bawah ↔ kanan atas)',
        description: 'Gerakkan beam secara diagonal',
        colorVar: SCREW_2_COLOR,
        axis: 'diagonal-up',
        minusLabel: 'ke kanan atas',
        plusLabel: 'ke kiri bawah',
        movement: {
          minus: { x: 1, y: 1, description: 'Kanan atas' },
          plus: { x: -1, y: -1, description: 'Kiri bawah' },
        },
        knob: { top: '78%', left: '13%' },
        badge: { top: '78%', left: '31%' },
        refBadge: { top: '88%', left: '-6%' },
        refArrow: { top: '66%', left: '-6%' },
        pod: { side: 'left', top: '80%' },
        guide: 'Skru 2 (bawah kiri) gerakkan beam secara diagonal (kiri bawah ↔ kanan atas)',
      },
      screw3: {
        id: 'screw3',
        number: 3,
        title: 'Skru 3 – Kiri / Kanan',
        extraTitle: '(bawah kanan)',
        description: 'Gerakkan beam kiri atau kanan',
        colorVar: SCREW_3_COLOR,
        axis: 'horizontal',
        minusLabel: 'ke kiri',
        plusLabel: 'ke kanan',
        movement: {
          minus: { x: -1, y: 0, description: 'Kiri' },
          plus: { x: 1, y: 0, description: 'Kanan' },
        },
        knob: { top: '83%', left: '85.5%' },
        badge: { top: '83%', left: '67%' },
        refBadge: { top: '68%', left: '106%' },
        refArrow: { top: '88%', left: '106%' },
        pod: { side: 'right', top: '84%' },
        guide: 'Skru 3 (bawah kanan) gerakkan beam kiri/kanan',
      },
    },
  },
}
export const DEFAULT_LEVEL_ID: LevelId = 'level1'
export const SCREW_ORDER: ScrewId[] = ['screw1', 'screw2', 'screw3']
